// main-vue 模块 i18n 字符串（Vue 版登录页 + 菜单卡片页特有 keys）
// 通用键已存在于 common.js，这里只补 main-vue 独有 keys

const strings = {
  en: {
    "MANAGE_DOCUMENTS": "Document management",
    "MANAGE_PRODUCTS": "Product management",
    "TRACK_CHANGES": "Change tracking",
    "SOCIAL_FEATURES": "Social features",
    "MANAGE_DOCUMENTS_STRINGS": [
      "Versioning, ACLs, workflows",
      "Office and PDF preview",
      "Folder tree, tags, search",
    ],
    "MANAGE_PRODUCTS_STRINGS": [
      "Product structure, BOM",
      "Effectivities, alternatives",
      "Part library, configurations",
    ],
    "TRACK_CHANGES_STRINGS": [
      "Issues, requests, orders",
      "Milestones, traceability",
      "Workflows on changes",
    ],
    "SOCIAL_FEATURES_STRINGS": [
      "Comments, notifications",
      "Tags, subscriptions",
      "Video conferencing",
    ],
    "LOGIN_3D_PLACEHOLDER": "3D scene (placeholder)",
    "FAILED_LOGIN": "Login failed. Check credentials.",
    "RECOVERY_REQUEST_SENT": "Recovery email sent. Check your inbox.",
    "RECOVER_OK": "Password updated. You can now log in.",
    "ACCOUNT_NOT_ENABLED_YET": "Account created but not enabled yet. Wait for administrator approval.",
    "DISCONNECTED": "You have been disconnected.",
    "CONNECTING": "Connecting...",
    "VUE_VERSION": "Vue version",
    "LEGACY_VERSION": "Legacy",
    "VUE_NOT_READY": "Vue rewrite not available yet",
    "COMPARE_NOTICE": "Each module exposes both Vue and Legacy versions for side-by-side manual comparison.",
    "VUE_MODULES_COUNT": "Vue versions available: {count} / {total}",
    "CARD_WORKSPACE_TITLE": "Workspace administration",
    "CARD_WORKSPACE_DESC": "Manage workspaces, users, groups, roles, ACLs.",
    "CARD_CHANGE_TITLE": "Change management",
    "CARD_CHANGE_DESC": "Issues, requests, orders, milestones, workflows.",
    "CARD_DOCUMENT_TITLE": "Document management",
    "CARD_DOCUMENT_DESC": "Folders, documents, versions, tags, search.",
    "CARD_ACCOUNT_TITLE": "My account",
    "CARD_ACCOUNT_DESC": "Profile, password, notifications, GCM.",
    "CARD_PRODUCT_MGMT_TITLE": "Product management",
    "CARD_PRODUCT_MGMT_DESC": "Products, baselines, snapshots.",
    "CARD_PRODUCT_STRUCT_TITLE": "Product structure",
    "CARD_PRODUCT_STRUCT_DESC": "BOM tree, 3D viewer, effectivities.",
    "CARD_ORG_TITLE": "Organization",
    "CARD_ORG_DESC": "Accounts, organization-wide settings.",
    "CARD_PARTS_TITLE": "Parts",
    "CARD_PARTS_DESC": "Part library, revisions, attributes.",
    "CARD_VISUAL_TITLE": "Visualization",
    "CARD_VISUAL_DESC": "3D viewer, markers, layers, conversations.",
    "CARD_DOCS_LEGACY_TITLE": "Documents (browser)",
    "CARD_DOCS_LEGACY_DESC": "Read-only document browsing.",
    "LOG_OUT": "Log out",
    "REGISTRATION": "Registration",
    "TERMS_OF_SERVICES": "Terms of services",
    "TERMS_OF_SERVICES_TEXT": "By creating an account you agree with the terms of services.",
    "CREATE_ID": "Create your account",
    "USER_ID": "Login",
    "FIRSTNAME_NAME": "First name and last name",
    "ENTER_ID": "Enter your login",
    "ENTER_NEW_PASSWORD": "Enter a new password",
    "CHOOSE_PROVIDER": "Choose a provider",
    "LOGIN_AN_OTHER_WAY": "Log in another way",
    "TIMEZONE": "Time zone",
    "LANGUAGE": "Language",
    "USER": "User",
    "CONNECTION": "Login",
    "RECOVERY": "Forgot password",
    "RECOVER": "Reset password",
  },
  fr: {
    "MANAGE_DOCUMENTS": "Gestion de documents",
    "MANAGE_PRODUCTS": "Gestion de produits",
    "TRACK_CHANGES": "Suivi des modifications",
    "SOCIAL_FEATURES": "Fonctionnalités sociales",
    "MANAGE_DOCUMENTS_STRINGS": [
      "Versionnage, ACL, workflows",
      "Aperçu Office et PDF",
      "Arborescence, tags, recherche",
    ],
    "MANAGE_PRODUCTS_STRINGS": [
      "Structure produit, nomenclature",
      "Effectivités, alternatives",
      "Bibliothèque de pièces",
    ],
    "TRACK_CHANGES_STRINGS": [
      "Problèmes, demandes, ordres",
      "Jalons, traçabilité",
      "Workflows de changement",
    ],
    "SOCIAL_FEATURES_STRINGS": [
      "Commentaires, notifications",
      "Tags, abonnements",
      "Visioconférence",
    ],
    "LOGIN_3D_PLACEHOLDER": "Scène 3D (à venir)",
    "FAILED_LOGIN": "Échec de connexion. Vérifiez vos identifiants.",
    "RECOVERY_REQUEST_SENT": "Email de récupération envoyé.",
    "RECOVER_OK": "Mot de passe mis à jour.",
    "ACCOUNT_NOT_ENABLED_YET": "Compte créé mais non activé. Attendez l'approbation.",
    "DISCONNECTED": "Vous avez été déconnecté.",
    "CONNECTING": "Connexion...",
    "VUE_VERSION": "Version Vue",
    "LEGACY_VERSION": "Original",
    "VUE_NOT_READY": "Réécriture Vue non disponible",
    "COMPARE_NOTICE": "Chaque module expose les deux versions pour comparaison manuelle.",
    "VUE_MODULES_COUNT": "Versions Vue disponibles : {count} / {total}",
    "LOG_OUT": "Déconnexion",
  },
  zh: {
    "MANAGE_DOCUMENTS": "文档管理",
    "MANAGE_PRODUCTS": "产品管理",
    "TRACK_CHANGES": "变更跟踪",
    "SOCIAL_FEATURES": "社交特性",
    "MANAGE_DOCUMENTS_STRINGS": [
      "版本控制、ACL、工作流",
      "Office 和 PDF 预览",
      "文件夹树、标签、搜索",
    ],
    "MANAGE_PRODUCTS_STRINGS": [
      "产品结构、BOM 清单",
      "有效性、替代件",
      "零件库、配置管理",
    ],
    "TRACK_CHANGES_STRINGS": [
      "问题、请求、变更单",
      "里程碑、可追溯性",
      "变更工作流",
    ],
    "SOCIAL_FEATURES_STRINGS": [
      "评论、通知",
      "标签、订阅",
      "视频会议",
    ],
    "LOGIN_3D_PLACEHOLDER": "3D 场景(占位中,待补)",
    "FAILED_LOGIN": "登录失败,请检查账号密码",
    "RECOVERY_REQUEST_SENT": "找回密码邮件已发送,请查收邮箱",
    "RECOVER_OK": "密码已更新,可重新登录",
    "ACCOUNT_NOT_ENABLED_YET": "账号已创建但未启用,请等待管理员审核",
    "DISCONNECTED": "您已退出登录",
    "CONNECTING": "登录中...",
    "VUE_VERSION": "Vue 版",
    "LEGACY_VERSION": "原版",
    "VUE_NOT_READY": "Vue 版尚未完成,敬请期待",
    "COMPARE_NOTICE": "每个模块同时提供 Vue 版与原版链接,便于人工对比测试。",
    "VUE_MODULES_COUNT": "已完成 Vue 化模块:{count} / {total}",
    "CARD_WORKSPACE_TITLE": "工作区管理",
    "CARD_WORKSPACE_DESC": "管理工作区、用户、用户组、角色、ACL。",
    "CARD_CHANGE_TITLE": "变更管理",
    "CARD_CHANGE_DESC": "问题、请求、变更单、里程碑、工作流。",
    "CARD_DOCUMENT_TITLE": "文档管理",
    "CARD_DOCUMENT_DESC": "文件夹、文档、版本、标签、搜索。",
    "CARD_ACCOUNT_TITLE": "我的账号",
    "CARD_ACCOUNT_DESC": "个人资料、密码、通知。",
    "CARD_PRODUCT_MGMT_TITLE": "产品管理",
    "CARD_PRODUCT_MGMT_DESC": "产品、基线、快照。",
    "CARD_PRODUCT_STRUCT_TITLE": "产品结构",
    "CARD_PRODUCT_STRUCT_DESC": "BOM 树、3D 查看器。",
    "CARD_ORG_TITLE": "组织管理",
    "CARD_ORG_DESC": "账户、组织级设置。",
    "CARD_PARTS_TITLE": "零件管理",
    "CARD_PARTS_DESC": "零件库、版本、属性。",
    "CARD_VISUAL_TITLE": "数据可视化",
    "CARD_VISUAL_DESC": "3D 查看器、标记、图层。",
    "CARD_DOCS_LEGACY_TITLE": "文档浏览",
    "CARD_DOCS_LEGACY_DESC": "只读文档浏览。",
    "LOG_OUT": "退出登录",
    "REGISTRATION": "注册账号",
    "TERMS_OF_SERVICES": "服务条款",
    "TERMS_OF_SERVICES_TEXT": "创建账号即表示同意服务条款。",
    "CREATE_ID": "创建您的账号",
    "USER_ID": "登录名",
    "FIRSTNAME_NAME": "姓名",
    "ENTER_ID": "请输入您的登录名",
    "ENTER_NEW_PASSWORD": "请输入新密码",
    "CHOOSE_PROVIDER": "选择登录方式",
    "LOGIN_AN_OTHER_WAY": "其他方式登录",
    "TIMEZONE": "时区",
    "LANGUAGE": "语言",
    "USER": "用户",
    "CONNECTION": "登录",
    "RECOVERY": "找回密码",
    "RECOVER": "重置密码",
  },
  ru: {
    "MANAGE_DOCUMENTS": "Управление документами",
    "MANAGE_PRODUCTS": "Управление продуктами",
    "TRACK_CHANGES": "Отслеживание изменений",
    "SOCIAL_FEATURES": "Социальные функции",
    "MANAGE_DOCUMENTS_STRINGS": [
      "Версии, ACL, рабочие процессы",
      "Просмотр Office и PDF",
      "Папки, теги, поиск",
    ],
    "MANAGE_PRODUCTS_STRINGS": [
      "Структура продукта, BOM",
      "Эффективность, альтернативы",
      "Библиотека деталей",
    ],
    "TRACK_CHANGES_STRINGS": [
      "Проблемы, запросы, заказы",
      "Этапы, прослеживаемость",
      "Рабочие процессы изменений",
    ],
    "SOCIAL_FEATURES_STRINGS": [
      "Комментарии, уведомления",
      "Теги, подписки",
      "Видеоконференции",
    ],
    "LOGIN_3D_PLACEHOLDER": "3D-сцена (заглушка)",
    "FAILED_LOGIN": "Ошибка входа.",
    "RECOVERY_REQUEST_SENT": "Письмо отправлено.",
    "RECOVER_OK": "Пароль обновлён.",
    "ACCOUNT_NOT_ENABLED_YET": "Аккаунт создан, ожидает одобрения.",
    "DISCONNECTED": "Вы вышли из системы.",
    "CONNECTING": "Подключение...",
    "VUE_VERSION": "Vue версия",
    "LEGACY_VERSION": "Оригинал",
    "VUE_NOT_READY": "Vue версия недоступна",
    "COMPARE_NOTICE": "Каждый модуль доступен в двух версиях для сравнения.",
    "VUE_MODULES_COUNT": "Vue версий: {count} / {total}",
    "LOG_OUT": "Выйти",
  },
}

export default strings
